			  -- PROJECT-- 

-- Hospital Patient Care Operations Analytics --

-- SPRINT 1 --
-- BUSINESS UNDERSTANDING AND DATA UNDERSTANDING --

-- 1.1 Company Background (DONE) --

-- 1.2 Role (DONE) --

-- 1.3 ER Diagram Interpretation (DONE) --

-- 1.4 Analytical Thinking from the ER Diagram --
-- NOTE: Queries are written after completion of sprint 2
-- 1.Management wants to identify patients who have booked multiple appointments. Which table and columns are needed? --
-- Tables and columns needed; 1. PATIENTS:PATIENT_ID,PATIENT_NAME 2. APPOINTMENTS: PATIENT_ID,APPOINTMENT_ID
-- Querry;
SELECT P.PATIENT_ID,P.PATIENT_NAME,
COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.PATIENT_ID,p.PATIENT_NAME
HAVING COUNT(A.APPOINTMENT_ID) > 1;

-- 2. Operations wants to identify appointments that required more than one treatment attempt. Where is this information found? --
-- Tables and columns needed; 1. TREATMENTS:TREATMENT_ID,APPOINTMENT_ID,TREATMENT_ATTEMPT
-- Querry;
SELECT APPOINTMENT_ID,TREATMENT_ID,TREATMENT_ATTEMPT
FROM TREATMENTS
WHERE TREATMENT_ATTEMPT > 1
ORDER BY TREATMENT_ATTEMPT;

-- 3. Patient Services wants to compare General, Corporate, and Insurance patients based on appointment activity. Which tables must be connected? --
-- Ans:Tables and columns needed; 1. PATIENTS:PATIENT_ID,PATIENT_TYPE 2. APPOINTMENTS: PATIENT_ID,APPOINTMENT_ID
SELECT P.PATIENT_TYPE,
COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM PATIENTS P
JOIN APPOINTMENTS A
    ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.PATIENT_TYPE
ORDER BY TOTAL_APPOINTMENTS;

-- 4. Operations wants to compare service types based on treatment duration and waiting time. Which tables are required? --
-- Ans: Tables and columns needed; 1. TREATMENTS:APPOINTMENT_ID,TREATMENT_DURATION_MIN,WAITING_TIME_MIN 2. APPOINTMENTS: SERVICE_TYPE,APPOINTMENT_ID
SELECT A.SERVICE_TYPE,
ROUND(AVG(T.TREATMENT_DURATION_MIN), 2) AS AVG_TREATMENT_DURATION,
ROUND(AVG(T.WAITING_TIME_MIN), 2) AS AVG_WAITING_TIME
FROM APPOINTMENTS A
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY A.SERVICE_TYPE
ORDER BY AVG_TREATMENT_DURATION DESC;

-- 5. The team wants to identify which doctors handled treatments and examine their recorded ratings. What information is needed? --
-- Ans:Tables and columns needed; 1. TREATMENTS:DOCTER_ID,TREATMENT_ID 2. DOCTERS:DOCTER_ID,DOCTER_NAME,RATING
SELECT D.DOCTER_ID,D.DOCTER_NAME,D.RATING,
COUNT(T.TREATMENT_ID) AS TOTAL_TREATMENTS
FROM DOCTERS D
JOIN TREATMENTS T
ON D.DOCTER_ID = T.DOCTER_ID
GROUP BY D.DOCTER_ID,D.DOCTER_NAME,D.RATING
ORDER BY TOTAL_TREATMENTS DESC;

-- 6. Operations wants to understand whether different room/equipment types are used for different service types. Which tables and columns are required? --
-- Ans: Tables and columns needed; 1. TREATMENTS:APPOINTMENT_ID,ROOM_ID 2. APPOINTMENTS:APPOINTMENT_ID,SERVICE_TYPE 3.ROOMS: ROOM_ID,ROOM_TYPE,EQUIPMENT_TYPE
SELECT A.SERVICE_TYPE,R.ROOM_TYPE,R.EQUIPMENT_TYPE,
COUNT(T.TREATMENT_ID) TT
FROM APPOINTMENTS A
JOIN TREATMENTS T 
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
JOIN ROOMS R 
ON T.ROOM_ID = R.ROOM_ID
GROUP BY  A.SERVICE_TYPE,R.ROOM_TYPE,R.EQUIPMENT_TYPE
ORDER BY TT DESC;

-- 7. Management wants to compare treatment performance across cities. What information must be connected? --
-- ANS:  Tables and columns needed; 1. TREATMENTS:APPOINTMENT_ID,STATUS,TREATMENT_DURATION_MIN,WAITITNG_TIME_MIN 2. PATIENTS: PATIENT_ID,CITY 3.APPOINTMENTS: PATIENT_ID,APPOINTMENT_ID
 SELECT P.CITY,
COUNT(t.TREATMENT_ID) AS TOTAL_TREATMENTS,
ROUND(AVG(t.TREATMENT_DURATION_MIN), 2) AS AVG_TREATMENT_DURATION,
ROUND(AVG(t.WAITING_TIME_MIN), 2) AS AVG_WAITING_TIME
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY P.CITY
ORDER BY TOTAL_TREATMENTS DESC;

-- 8. Operations wants to investigate whether higher-priority appointments have longer waiting times or different outcomes. What information is needed? --
-- ANS: Tables and columns needed; 1. TREATMENTS:APPOINTMENT_ID,STATUS,WAITITNG_TIME_MIN 2. APPOINTMENTS: PATIENT_ID,PRIORITY
SELECT A.PRIORITY,
COUNT(T.TREATMENT_ID) AS TOTAL_TREATMENTS,
ROUND(AVG(T.WAITING_TIME_MIN), 2) AS AVG_WAITING_TIME,
T.STATUS, COUNT(*) AS STATUS_COUNT
FROM APPOINTMENTS A
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY A.PRIORITY,T.STATUS
ORDER BY A.PRIORITY,STATUS_COUNT DESC;

-- 9. Management wants to understand whether treatment outcomes differ across service types. What tables and fields should be combined? --
-- ANS: Tables and columns needed; 1. TREATMENTS:APPOINTMENT_ID,STATUS 2. APPOINTMENTS: APPOINTMENT_ID, SERVICE_TYPE
SELECT A.SERVICE_TYPE,T.STATUS,
COUNT(T.TREATMENT_ID) AS TREATMENT_COUNT
FROM APPOINTMENTS A
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY A.SERVICE_TYPE,T.STATUS
ORDER BY A.SERVICE_TYPE,TREATMENT_COUNT DESC;

-- 10. The Patient Services team wants to connect each patient to their appointments and treatment outcomes. What relationships are required? --
-- ANS: Tables and columns needed; 1. TREATMENTS:APPOINTMENT_ID,STATUS 2. PATIENTS: PATIENT_ID,PATIENT_NAME 3.APPOINTMENTS: STATUS,APPOINTMENT_ID
SELECT P.PATIENT_ID,P.PATIENT_NAME,A.APPOINTMENT_ID,T.TREATMENT_ID,T.STATUS AS TREATMENT_OUTCOME
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
ORDER BY P.PATIENT_ID, A.APPOINTMENT_ID;


-- SPRINT 2 -- 
-- DATABASE SETUP --

# CREATING A DATABASE {CarePlus Hospital}
CREATE DATABASE CAREPLUS_HSPTL;

#USING DATABASE
USE CAREPLUS_HSPTL;

# CREATING TABLES
#TABLE 1. {PATIENTS}
CREATE TABLE PATIENTS
(
PATIENT_ID VARCHAR(20) PRIMARY KEY,
PATIENT_NAME VARCHAR(100) NOT NULL,
AGE INT NOT NULL,
GENDER VARCHAR(10) NOT NULL,
CITY VARCHAR(50),
PATIENT_TYPE VARCHAR(20),
PREFERRED_TIME_SLOT VARCHAR(20) NOT NULL,
REGISTRATION_DATE DATE NOT NULL
);
SELECT * FROM PATIENTS;

# TABLE 2. {ROOMS}
CREATE TABLE ROOMS
(
ROOM_ID VARCHAR(10) PRIMARY KEY,
ROOM_TYPE VARCHAR(30) NOT NULL,
FLOOR INT NOT NULL,
EQUIPMENT_TYPE VARCHAR(50) NOT NULL,
CAPACITY INT,
LAST_MAINTAINANCE_DATE DATE NOT NULL,
IS_AVAILABLE VARCHAR(3) NOT NULL
);
SELECT * FROM ROOMS;

# TABLE 3. {DOCTERS}
CREATE TABLE DOCTERS
(
DOCTER_ID VARCHAR(10) PRIMARY KEY,
DOCTER_NAME VARCHAR(100) NOT NULL,
SPECIALITY VARCHAR(50) NOT NULL,
HIRE_DATE DATE,
RATING DECIMAL(3,2) NOT NULL,
EMPLOYEMENT_TYPE VARCHAR(20) NOT NULL,
IS_ACTIVE VARCHAR(3) NOT NULL
);
SELECT * FROM DOCTERS;

# TABLE 4. {APPOINTMENTS}
CREATE TABLE APPOINTMENTS
(
APPOINTMENT_ID VARCHAR(20) PRIMARY KEY,
PATIENT_ID VARCHAR(20),
foreign key (PATIENT_ID) references PATIENTS(PATIENT_ID),
APPOINTMENT_DATE DATE,
DOCTER_ID VARCHAR(10),
foreign key (DOCTER_ID) references DOCTERS(DOCTER_ID),
SERVICE_TYPE VARCHAR(30),
PRIORITY VARCHAR(10),
ESTIMATED_COST DECIMAL(10,2) NOT NULL,
BOOKING_CHANEL VARCHAR(20)
);
SELECT * FROM APPOINTMENTS;

#TABLE 5. {TREATMENTS}
CREATE TABLE TREATMENTS
(
TREATMENT_ID VARCHAR(20) PRIMARY KEY,
APPOINTMENT_ID VARCHAR(20),
foreign key (APPOINTMENT_ID) references APPOINTMENTS(APPOINTMENT_ID),
DOCTER_ID VARCHAR(10),
foreign key (DOCTER_ID) references DOCTERS(DOCTER_ID),
ROOM_ID VARCHAR(10),
foreign key (ROOM_ID) references ROOMS(ROOM_ID),
ACTUAL_TREATMENT_DATE DATE NOT NULL,
STATUS VARCHAR(20) NOT NULL,
TREATMENT_ATTEMPT INT,
TREATMENT_DURATION_MIN INT,
WAITING_TIME_MIN INT,
TREATMENT_COST DECIMAL(10,2) NOT NULL
);
SELECT * FROM TREATMENTS;

-- SPRINT 3 --
-- Basic Analysis / Data Exploration --

-- 1. What is the total number of patients? --
 SELECT COUNT(PATIENT_ID) AS TNP
 FROM PATIENTS;
 
-- 2. What is the total number of appointments? --
SELECT COUNT(APPOINTMENT_ID) AS TOTAL_NUMBER_OF_APPOINTMNETS 
FROM APPOINTMENTS;

-- 3. What is the total number of treatment records? --
SELECT COUNT(TREATMENT_ID) AS TOTAL_NUMBER_OF_TREATMENTS 
FROM TREATMENTS;

-- 4. What are the different medical service types? --
SELECT DISTINCT SERVICE_TYPE AS SERVICE_TYPES 
FROM APPOINTMENTS;

-- 5. How many doctors are currently active? --
SELECT COUNT(IS_ACTIVE) AS DOCTERS_CURRENTLY_ACTIVE 
FROM DOCTERS
WHERE IS_ACTIVE = "Yes";

-- 6. What are the different room types? --
SELECT DISTINCT ROOM_TYPE AS different_room_types
FROM ROOMS;

-- 7. What is the total estimated appointment value? --
SELECT SUM(ESTIMATED_COST) AS estimated_appointment_value
FROM APPOINTMENTS;

-- 8. What is the average treatment duration? --
SELECT AVG(TREATMENT_DURATION_MIN) AS average_treatment_duration
FROM TREATMENTS;

-- Sprint 4 -

-- Objective-Based Analysis --

-- 4.1 Understand Patient and Appointment Demand --
-- ● Compare appointment volume across cities. --
SELECT P.CITY, 
COUNT(A.APPOINTMENT_ID) AS APPOINTMENT_VOLUME
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.CITY
ORDER BY APPOINTMENT_VOLUME
DESC;

-- ● Compare appointments across service types and priorities. --
SELECT SERVICE_TYPE,PRIORITY,
COUNT(APPOINTMENT_ID) AS APPOINTMENT_VOLUME
FROM APPOINTMENTS
GROUP BY  SERVICE_TYPE,PRIORITY
ORDER BY APPOINTMENT_VOLUME 
DESC;

-- ● Examine appointment volume over time. -- 
SELECT  YEAR(APPOINTMENT_DATE) AS YEAR,
MONTH(APPOINTMENT_DATE) AS MONTH,
COUNT(APPOINTMENT_ID) AS APPOINTMENT_VOLUME
FROM APPOINTMENTS
GROUP BY YEAR(APPOINTMENT_DATE),MONTH(APPOINTMENT_DATE)
ORDER BY YEAR,MONTH;

-- ● Compare estimated appointment value across patient types. --
SELECT P.PATIENT_TYPE,SUM(A.ESTIMATED_COST) AS TOTAL_ESTIMATED_VALUE
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.PATIENT_TYPE
ORDER BY TOTAL_ESTIMATED_VALUE 
DESC;

-- ● Examine booking channels and their contribution to demand. --
SELECT BOOKING_CHANEL,COUNT(APPOINTMENT_ID) AS APPOINTMENT_VOLUME
FROM APPOINTMENTS
GROUP BY BOOKING_CHANEL
ORDER BY APPOINTMENT_VOLUME
DESC;


-- 4.2 Understand Patient Appointment Behaviour --
-- ● Compare patients by number of appointments. --
-- Find out how many appointments each patient has booked.
SELECT P.PATIENT_ID,P.PATIENT_NAME,
COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.PATIENT_ID,P.PATIENT_NAME
ORDER BY TOTAL_APPOINTMENTS 
DESC;

-- ● Identify patients with higher cumulative estimated appointment value. --
-- Find patients whose appointments have the highest total estimated cost.
SELECT P.PATIENT_ID,P.PATIENT_NAME,
SUM(A.ESTIMATED_COST) AS CEAV
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.PATIENT_ID,P.PATIENT_NAME
ORDER BY CEAV
DESC;

-- ● Compare patient activity across cities. --
-- Determine which cities have the most active patients.
-- Here we can measure activity using the number of appointments.
SELECT P.CITY,
COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
COUNT(DISTINCT P.PATIENT_ID) AS ACTIVE_PATIENTS
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.CITY
ORDER BY TOTAL_APPOINTMENTS 
DESC;

-- ● Compare General, Corporate, and Insurance patients. --
-- Compare patient categories based on their appointment activity.
SELECT P.PATIENT_TYPE,
COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
COUNT(DISTINCT P.PATIENT_ID) AS TOTAL_PATIENTS,
SUM(A.ESTIMATED_COST) AS TOTAL_ESTIMATED_VALUE
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
GROUP BY P.PATIENT_TYPE
ORDER BY TOTAL_APPOINTMENTS 
DESC;

-- ● Examine patient booking patterns over time. --
-- Understand how patient appointment activity changes month by month.
SELECT DATE_FORMAT(A.APPOINTMENT_DATE, '%Y-%m') AS APPOINTMENT_MONTH,
COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
COUNT(DISTINCT A.PATIENT_ID) AS ACTIVE_PATIENTS
FROM APPOINTMENTS A
GROUP BY DATE_FORMAT(A.APPOINTMENT_DATE, '%Y-%m')
ORDER BY APPOINTMENT_MONTH;


-- 4.3 Evaluate Treatment Performance --
-- ● Compare treatment outcomes across cities. --
-- Find out how treatment outcomes differ from one city to another.
SELECT P.CITY, T.STATUS,
COUNT(T.TREATMENT_ID) AS TREATMENT_COUNT
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY P.CITY,T.STATUS
ORDER BY TREATMENT_COUNT 
DESC;
    
-- ● Examine treatment duration and waiting time. --
-- Understand how long treatments take and how long patients wait.
SELECT STATUS,
COUNT(TREATMENT_ID) AS TREATMENT_COUNT,
ROUND(AVG(TREATMENT_DURATION_MIN), 2) AS AVG_DURATION_MIN,
ROUND(AVG(WAITING_TIME_MIN), 2) AS AVG_WAITING_MIN
FROM TREATMENTS
GROUP BY STATUS
ORDER BY TREATMENT_COUNT 
DESC;

-- ● Compare Completed, Cancelled, No-Show, Rescheduled, and In Progress outcomes. --
-- Count how many treatments fall into each outcome/status.
SELECT STATUS,
COUNT(TREATMENT_ID) AS TREATMENT_COUNT
FROM TREATMENTS
GROUP BY STATUS
ORDER BY TREATMENT_COUNT 
DESC;

-- ● Identify areas with higher treatment activity or poorer outcomes. --
-- Here, area = city, because CITY is stored in the PATIENTS table.
SELECT P.CITY,
COUNT(T.TREATMENT_ID) AS TOTAL_TREATMENTS,
SUM(CASE WHEN T.STATUS = 'Completed' THEN 1 ELSE 0 END) AS COMPLETED,
SUM(CASE WHEN T.STATUS = 'Cancelled' THEN 1 ELSE 0 END) AS CANCELLED,
SUM(CASE WHEN T.STATUS = 'Rescheduled' THEN 1 ELSE 0 END) AS RESCHEDULED,
SUM(CASE WHEN T.STATUS = 'No-Show' THEN 1 ELSE 0 END) AS NO_SHOW
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY P.CITY
ORDER BY TOTAL_TREATMENTS 
DESC;

-- ● Compare treatment performance over time. --
-- Understand whether treatment activity and performance are changing month by month.
SELECT DATE_FORMAT(ACTUAL_TREATMENT_DATE, '%Y-%m') AS TREATMENT_MONTH,
COUNT(TREATMENT_ID) AS TOTAL_TREATMENTS,
ROUND(AVG(TREATMENT_DURATION_MIN), 2) AS AVG_TREATMENT_DURATION,
ROUND(AVG(WAITING_TIME_MIN), 2) AS AVG_WAITING_TIME
FROM TREATMENTS
GROUP BY DATE_FORMAT(ACTUAL_TREATMENT_DATE, '%Y-%m')
ORDER BY TREATMENT_MONTH;


-- 4.4 Understand Doctor and Room Performance
-- ● Compare the number of treatments handled by doctors.
SELECT D.DOCTER_ID,D.DOCTER_NAME,
COUNT(T.TREATMENT_ID) AS TOTAL_TREATMENTS
FROM DOCTERS D
JOIN TREATMENTS T
ON D.DOCTER_ID = T.DOCTER_ID
GROUP BY D.DOCTER_ID,D.DOCTER_NAME
ORDER BY TOTAL_TREATMENTS 
DESC;

-- ● Compare doctor performance across treatment outcomes.
SELECT D.DOCTER_ID,D.DOCTER_NAME,T.STATUS,
COUNT(T.TREATMENT_ID) AS N_O_T
FROM DOCTERS D
JOIN TREATMENTS T 
ON D.DOCTER_ID =T.DOCTER_ID
GROUP BY D.DOCTER_ID,D.DOCTER_NAME,T.STATUS
ORDER BY D.DOCTER_NAME,N_O_T
DESC;

-- ● Examine treatment duration across doctors.
-- Determine how much time each doctor spends on treatments on average.
SELECT D.DOCTER_ID,D.DOCTER_NAME,D.SPECIALITY,T.TREATMENT_ATTEMPT,
COUNT(TREATMENT_ID) AS TOTAL_TREATMENTS,
ROUND(AVG(T.TREATMENT_DURATION_MIN), 2) AS AVG_T_D
FROM DOCTERS D
JOIN TREATMENTS T 
ON D.DOCTER_ID = T.DOCTER_ID
GROUP BY D.DOCTER_ID,D.DOCTER_NAME,D.SPECIALITY,T.TREATMENT_ATTEMPT
ORDER BY  AVG_T_D;

-- B ● Treatment Duration and waiting time
 SELECT AVG(TREATMENT_DURATION_MIN) AS AVG_TREATMENT_DURATION,
       AVG(WAITING_TIME_MIN) AS AVG_WAITING_TIME,
       MIN(TREATMENT_DURATION_MIN) AS MIN_TREATMENT_DURATION,
       MAX(TREATMENT_DURATION_MIN) AS MAX_TREATMENT_DURATION,
       MIN(WAITING_TIME_MIN) AS MIN_WAITING_TIME,
       MAX(WAITING_TIME_MIN) AS MAX_WAITING_TIME
FROM TREATMENTS; 

-- ●  Compare room usage across room types and equipment types.
SELECT R.ROOM_TYPE,R.EQUIPMENT_TYPE,
COUNT(T.TREATMENT_ID) AS TT
FROM ROOMS R 
JOIN TREATMENTS T 
ON R.ROOM_ID = T.ROOM_ID
GROUP BY R.ROOM_TYPE,R.EQUIPMENT_TYPE 
ORDER BY TT
DESC;

-- ● Evaluate treatment performance across rooms.
SELECT R.ROOM_ID,R.ROOM_TYPE,R.EQUIPMENT_TYPE,
COUNT(T.TREATMENT_ID) AS TOTAL_TREATMENTS,
ROUND(AVG(T.TREATMENT_DURATION_MIN), 2) AS AVG_TREATMENT_DURATION,
ROUND(AVG(T.WAITING_TIME_MIN), 2) AS AVG_WAITING_TIME
FROM ROOMS R
JOIN TREATMENTS T
ON R.ROOM_ID = T.ROOM_ID
GROUP BY R.ROOM_ID,R.ROOM_TYPE,R.EQUIPMENT_TYPE
ORDER BY TOTAL_TREATMENTS 
DESC;


-- 4.5 Identify Treatment and Appointment Problems
-- ● Identify appointments requiring multiple treatment attempts.
SELECT A.APPOINTMENT_ID,A.PATIENT_ID,T.TREATMENT_ID,T.TREATMENT_ATTEMPT
FROM APPOINTMENTS A
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
WHERE T.TREATMENT_ATTEMPT > 1
ORDER BY T.TREATMENT_ATTEMPT 
DESC;

-- ●	Find common problem statuses and patterns.
-- Identify which treatment statuses occur most frequently.
SELECT STATUS,
COUNT(TREATMENT_ID) AS TREATMENT_COUNT
FROM TREATMENTS
GROUP BY STATUS
ORDER BY TREATMENT_COUNT 
DESC;

-- ● Compare waiting time for appointments with multiple attempts.
-- Determine whether appointments requiring multiple treatment attempts have different waiting times.
SELECT CASE WHEN TREATMENT_ATTEMPT > 1 THEN 'Multiple Attempts' ELSE 'Single Attempt' END AS ATTEMPT_GROUP,
COUNT(TREATMENT_ID) AS TREATMENT_COUNT,
ROUND(AVG(WAITING_TIME_MIN), 2) AS AVG_WAITING_TIME
FROM TREATMENTS
GROUP BY CASE WHEN TREATMENT_ATTEMPT > 1 THEN 'Multiple Attempts' ELSE 'Single Attempt' END
ORDER BY AVG_WAITING_TIME 
DESC;

-- ●	Identify cities or service types with more cancellations, no-shows, or rescheduling.
-- A. Compare problem outcomes across cities
SELECT P.CITY,
SUM(CASE WHEN T.STATUS = 'Cancelled' THEN 1 ELSE 0 END) AS CANCELLED,
SUM(CASE WHEN T.STATUS = 'No-Show' THEN 1 ELSE 0 END) AS NO_SHOW,
SUM(CASE WHEN T.STATUS = 'Rescheduled' THEN 1 ELSE 0 END) AS RESCHEDULED
FROM PATIENTS P
JOIN APPOINTMENTS A
ON P.PATIENT_ID = A.PATIENT_ID
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY P.CITY
ORDER BY CANCELLED DESC,NO_SHOW DESC,RESCHEDULED 
DESC;
    
-- B. Compare problem outcomes across service types
SELECT A.SERVICE_TYPE,
SUM(CASE WHEN T.STATUS = 'Cancelled' THEN 1 ELSE 0 END) AS CANCELLED,
SUM(CASE WHEN T.STATUS = 'No-Show' THEN 1 ELSE 0 END) AS NO_SHOW,
SUM(CASE WHEN T.STATUS = 'Rescheduled' THEN 1 ELSE 0 END) AS RESCHEDULED
FROM APPOINTMENTS A
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY A.SERVICE_TYPE
ORDER BY CANCELLED DESC,
NO_SHOW DESC,
RESCHEDULED DESC;
    
-- ●	Investigate whether priority level is associated with waiting time or treatment outcomes.
SELECT A.PRIORITY,
COUNT(T.TREATMENT_ID) AS TREATMENT_COUNT,
ROUND(AVG(T.WAITING_TIME_MIN), 2) AS AVG_WAITING_TIME
FROM APPOINTMENTS A
JOIN TREATMENTS T
ON A.APPOINTMENT_ID = T.APPOINTMENT_ID
GROUP BY A.PRIORITY
ORDER BY AVG_WAITING_TIME 
DESC;






